"""Shared text feature extraction for training and inference."""

from text_features.text import (
    SENTENCE_SPLIT_RE,
    WORD_RE,
    TextChunk,
    chunk_text,
    clamp,
    mean,
    normalize_text,
    safe_std,
    split_paragraphs,
    split_sentences,
    text_length_bucket,
    tokenize_words,
)
from text_features.features import (
    COMMON_TRANSITIONS,
    META_FEATURE_NAMES,
    STOPWORDS,
    STYLOMETRY_FEATURE_NAMES,
    compute_document_consistency,
    compute_stylometric_features,
    model_agreement,
    quality_penalty_for,
    shannon_entropy,
    sigmoid,
    stopword_ratio,
    stylometric_feature_map,
    stylometric_feature_vector,
)

__all__ = [
    "COMMON_TRANSITIONS",
    "META_FEATURE_NAMES",
    "SENTENCE_SPLIT_RE",
    "STOPWORDS",
    "STYLOMETRY_FEATURE_NAMES",
    "TextChunk",
    "WORD_RE",
    "chunk_text",
    "clamp",
    "compute_document_consistency",
    "compute_stylometric_features",
    "mean",
    "model_agreement",
    "normalize_text",
    "quality_penalty_for",
    "safe_std",
    "shannon_entropy",
    "sigmoid",
    "split_paragraphs",
    "split_sentences",
    "stopword_ratio",
    "stylometric_feature_map",
    "stylometric_feature_vector",
    "text_length_bucket",
    "tokenize_words",
]
