apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-text-detector-data
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-text-detector-artifacts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-text-detector-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
